### ISSUE TITLE
Dutch translation of airrohr and dnms building instructions?

### ISSUE THREAD

**Issue by pe0ter** [opendata-stuttgart/sensor.community#128]
The dutch language page of sensor.community/nl, 'build your own sensor' points to english airrohr and dnms instructions.
Would it be possible to add a dutch version of both instructions?
I can fork the english version and translate them but I noticed there is no NL folder on github to store these translations

**Comment by ohheyitsdave** [comment]
Hi @pe0ter 

English is the fallback language. You can just follow the chapter translation in the README.md 👉[Translation](https://github.com/opendata-stuttgart/sensor.community#translation)
Just have to copy some folders,  translate a few markdown-files and do some changes in a few files. 
It should take around 1-2 hours max.

**FYI** betrik did a commit for the airRohr-guide. 
👉 https://github.com/opendata-stuttgart/sensor.community/pull/129

Best regards
David

**Comment by evertkuiken** [comment]
The airrohr part has been translated by @bertrik and I am making some small changes to the text right now. I don't know the DNMS part, but when I find the time, I will try to do a translation.

**Comment by pe0ter** [comment]
Super, this is great, much appreciated.
