### ISSUE TITLE
missing content or links wrong (404)

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/sensor.community#24]
404 on links [0] and [1]

> [Build your own sensor][0] and become part of the [worldwide Civic Tech network 🌐][1]

> [0]: en/docs/
> [1]: en/community/
> published from :[Build a DIY sensor and become part of the worldwide citizen science, open data, civic tech network. Supported by a lot of contributors 💕](https://sensor.community/en/)

**Comment by Marwe** [comment]
Nearly all campaigns, too...
Only some (external) links work, [0] leads to 404

> ## Join a campaign
> 
> [#Sensor2Library Sensor.Community][0][️#NO2 Sensor.Community][0][️#Sensor@RefS Sensor.Community][0][️#zero200 Sensor.Community][0][#GlobalGoals United Nations SDG][1][️#EC2020 Wilson Center & EPA][2][️#CAD2020 Clean Air Day][3][️#Sensor2School Sensor.Community][0]
> 
> [0]: en/campaign
> [1]: https://sustainabledevelopment.un.org/?menu=1300
> [2]: https://www.earthday.org/earth-day-2020/
> [3]: https://cleanairday.eu/
> 
> published from :[Build a DIY sensor and become part of the worldwide citizen science, open data, civic tech network. Supported by a lot of contributors 💕](https://sensor.community/en/)

**Comment by ohheyitsdave** [comment]
fixed. published on stage server
