### ISSUE TITLE
HTML Tags missing

### ISSUE THREAD

**Issue by ohheyitsdave** [opendata-stuttgart/sensor.community#33]
On sapper export </body> and closing </html> Tag is missing

**Comment by ohheyitsdave** [comment]
Not a bug 👉  [#1061](https://github.com/sveltejs/sapper/issues/1061). Currently no way to deactivate it 👉  [#348](https://github.com/sveltejs/sapper/issues/348).

There is a [fork](https://github.com/aubergene/sapper/commit/170b43e881eef1eb099236834cc35145bbf2d4fa) to solve that issue, but it's not up to date.

**Comment by ricki-z** [comment]
This may be solved with an upcoming release of svelte (if a configuration of html-minimize is possible).
So the issue should be open as a reminder.

**Comment by ricki-z** [comment]
is working with div with id.
