### ISSUE TITLE
Map und API slow

### ISSUE THREAD

**Issue by DasNordlicht** [opendata-stuttgart/sensor.community#62]
Is it possible that the map and the API are extremely slow at the moment?

**Comment by ricki-z** [comment]
Is it possible that many site are sometimes slow at the moment with all the people streaming, having video calls, working the whole time from home ...
And sometimes some people seem to have too much time and are requesting the map more often than really needed.
This is a project maintained and organized by volunteers. We have only a limited amount of time and no unlimited budget for servers.
